<?php
	include("../database/database_connection.php");
  	include_once('../functions/login_functions.php');
 	verify_valid_system_user();

 	$system_user = $_SESSION['valid_dts_user'];
	$qry_access = mysqli_query($connection,"select * from tbl_users where username='$system_user'");
	$access = mysqli_fetch_assoc($qry_access);
?>
<!DOCTYPE html>
<html>
<head>
	<title>Document Tracking System</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css">
	<script src="../bootstrap/js/jquery.min.js"></script>
	<script src="../bootstrap/js/bootstrap.min.js"></script>
	<!-- other css -->
	<link rel="stylesheet" href="../bootstrap/css/designs.min.css">

	<!-- For Tables -->
	<link rel="stylesheet" href="../bootstrap/css/dataTables.min.css">
	<script type="text/javascript" src="../bootstrap/js/dataTables.min.js"></script>
	<link rel="icon" href="../images/dts.png" type="image/gif" sizes="16x16">
</head>
<body>
	
	<div class="container-report-delin">
		<table class="table-report">
			<tr>
				<td colspan="2" style="text-align: center;"><h4>DOCUMENT TRACKING SYSTEM REPORT</h4></td>
			</tr>
			<tr>
				<td style="width:150px;">REPORT TYPE:</td>
				<td>For Due</td>
			</tr>
			<tr>
				<td style="width:150px;">DATE:</td>
				<td><?php echo date('F Y')?></td>
			</tr>
		</table>
		<br>
		<table class="table-report" border="1">
			<tr align="center" style="font-weight: bold;">
				<td width="30px;">#</td>
				<td>Barcode</td>
				<td>Doc. Type</td>
				<td>Source</td>
				<td width="400px;">Subject Matter</td>
				<td>Routed To</td>
			</tr>
			<?php
				$datenow = date("Y-m-d");
				$date1 = str_replace('-', '/', $datenow);
				$tomorrow = date('Y-m-d',strtotime($date1 . "+1 days"));
				
				$current = date("Y-m");

				//$qry_for_due = mysqli_query($connection,"select * from tbl_document where recieve_date like '$current%' and datediff(end_date,'$datenow')<1 and transaction_end_date='0000-00-00'");
				$qry_for_due = mysqli_query($connection,"select * from tbl_document where end_date like '$tomorrow%' and status!=0 and transaction_end_date='0000-00-00'");

				for($a=1;$a<=mysqli_num_rows($qry_for_due);$a++){
					$rows = mysqli_fetch_assoc($qry_for_due);
					echo "<tr>";
					echo "<td align='center'>$a</td>";
					echo "<td align='center'><a href='../forms/tracking_result.php?barcode=$rows[barcode]&acode=$rows[access_code]' target='_blank'>$rows[barcode]</a></td>";
					echo "<td align='center'>$rows[document_type]</td>";
					echo "<td>&nbsp;".ucwords($rows['source_name'])."</td>";
					echo "<td style='padding:2px;'>$rows[subject_matter]</td>";

					$qry_current = mysqli_query($connection,"select * from tbl_document_transaction where barcode='$rows[barcode]' and status='1'");
					$data = mysqli_fetch_assoc($qry_current);


					echo "<td align='center'>$data[route_office_code]</td>";
					echo "</tr>";
				}

			?>
		</table>
		
		Generated By: <?php echo $_REQUEST['user']; ?>
		<br>
		Date: <?php echo date("M d, Y");?>

	</div>
</body>
</html>