<?php
 
	include("../database/database_connection.php");
  	include_once('../functions/login_functions.php');
 	verify_valid_system_user();

 	$system_user = $_SESSION['valid_dts_user'];
	//$qry_access = mysqli_query($connection,"select * from tbl_users where username='$system_user'");
	//$access = mysqli_fetch_assoc($qry_access);
?>
<!DOCTYPE html>
<html>
<head>
	<title>Document Tracking System</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css">
	<script src="../bootstrap/js/jquery.min.js"></script>
	<script src="../bootstrap/js/bootstrap.min.js"></script>
	<!-- other css -->
	<link rel="stylesheet" href="../bootstrap/css/designs.min.css">

	<!-- For Tables -->
	<link rel="stylesheet" href="../bootstrap/css/dataTables.min.css">
	<script type="text/javascript" src="../bootstrap/js/dataTables.min.js"></script>
	<link rel="icon" href="../images/dts.png" type="image/gif" sizes="16x16">
</head>
<body>
	<?php
	/*------------date-------------------*/
	//$date_display = $_REQUEST['frommm']."/".$_REQUEST['fromyyyy'];
	
	//$date = $_REQUEST['fromyyyy']."-".$_REQUEST['frommm'];

	?>
	<div class="container-report-delin">
		<table class="table-report">
			<tr>
				<td colspan="2" style="text-align: center;"><h4>DOCUMENT TRACKING SYSTEM REPORT</h4></td>
			</tr>
			<tr>
				<td style="width:150px;">REPORT TYPE:</td>
				<td>Office Performance</td>
			</tr>
			<tr>
				 
				<td><?php //echo $date_display; ?></td>
			</tr>
		</table>
		<br>
		<table class="table-report" border="1">
			<tr align="center" style="font-weight: bold;">
				<td rowspan="2">Code</td>
				<td rowspan="2">Office Name</td>
				<td colspan="3">Transactions</td>
			</tr>
			<tr align="center" style="font-weight: bold;">
				<td width="100px;">To-Do</td>
				<td width="100px;">Received</td>
				<td width="100px;">Completed</td>
			</tr>
			<?php
			$totaltodo = 0;
			$totalrec = 0;
			$totaldone = 0;
			$qry_office = mysqli_query($connection,"select * from tbl_office order by office_name asc");
			for($a=1;$a<=mysqli_num_rows($qry_office);$a++){
				$rows = mysqli_fetch_assoc($qry_office);
				$qry_todo = $qry_to_office = mysqli_query($connection,"select * from tbl_document_transaction a, tbl_document b where a.route_office_code='$rows[office_code]' and a.current_action='REL' and a.barcode=b.barcode");
 
				$qry_rec = mysqli_query($connection,"select * from tbl_document_transaction a, tbl_document b where a.office_code='$rows[office_code]' and (a.current_action='REC') and a.barcode=b.barcode");

				$qry_done = mysqli_query($connection,"select * from tbl_document_transaction a, tbl_document b where a.office_code='$rows[office_code]' and (a.current_action='END' || a.current_action='') and a.barcode=b.barcode");

				$todo = mysqli_num_rows($qry_todo);
				$done = mysqli_num_rows($qry_done);
				$rec = mysqli_num_rows($qry_rec);
				$totaltodo+=$todo;
				$totaldone+=$done;
				$totalrec+=$rec;

				if($todo > 20 || $rec > 20) {
					echo "<tr style='background-color:#ff000040;'>";
				} 
				else {
					echo "<tr>";	
				}
				
				echo "<td>&nbsp;&nbsp;$rows[office_code]</td>";

				echo "<td>&nbsp;&nbsp;$rows[office_name]</td>";

				 
				
				
				echo "<td align='center'>".number_format($todo)."</td>";
				echo "<td align='center'>".number_format($rec)."</td>";
				echo "<td align='center'>".number_format($done)."</td>";
				echo "</tr>";
			}

			?>
			<tr>
				<th colspan="2" >Sub-total</th>
				<th align='center'><?php echo $totaltodo; ?></th>
				<th align='center'><?php echo $totalrec; ?></th>
				<th align='center'><?php echo $totaldone; ?></th>
			</tr>
			 
		</table>
		<br>
		Generated By: <?php echo $_REQUEST['user']; ?>
		<br>
		Date: <?php echo date("M d, Y");?>

	</div>
</body>
</html>
