<?php
 
	include("../database/database_connection.php");
  	include_once('../functions/login_functions.php');
 	verify_valid_system_user();

 	$system_user = $_SESSION['valid_dts_user'];
	$qry_access = mysqli_query($connection,"select * from tbl_users where username='$system_user'");
	$access = mysqli_fetch_assoc($qry_access);
?>
<!DOCTYPE html>
<html>
<head>
	<title>Document Tracking System</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css">
	<script src="../bootstrap/js/jquery.min.js"></script>
	<script src="../bootstrap/js/bootstrap.min.js"></script>
	<!-- other css -->
	<link rel="stylesheet" href="../bootstrap/css/designs.min.css">

	<!-- For Tables -->
	<link rel="stylesheet" href="../bootstrap/css/dataTables.min.css">
	<script type="text/javascript" src="../bootstrap/js/dataTables.min.js"></script>
	<link rel="icon" href="../images/dts.png" type="image/gif" sizes="16x16">
</head>
<body>
	<?php
	/*------------date-------------------*/
	//$date_display = $_REQUEST['frommm']."/".$_REQUEST['fromyyyy'];
	
	//$date = $_REQUEST['fromyyyy']."-".$_REQUEST['frommm'];

	?>
	<div class="container-report-delin">
		<table class="table-report">
			<tr>
				<td colspan="2" style="text-align: center;"><h4>DOCUMENT TRACKING SYSTEM REPORT</h4></td>
			</tr>
			<tr>
				<td style="width:150px;">REPORT TYPE:</td>
				<td>Office Performance</td>
			</tr>
			<tr>
				 
				<td><?php //echo $date_display; ?></td>
			</tr>
		</table>
		<br>
		<table class="table-report" border="1">
			<tr align="center" style="font-weight: bold;">
				<td rowspan="2">Code</td>
				<td rowspan="2">Office Name</td>
				<td colspan="3">Transactions</td>
			</tr>
			<tr align="center" style="font-weight: bold;">
				<td width="100px;">On-time</td>
				<td width="100px;">Deliquent</td>
				<td width="100px;">Total</td>
			</tr>
			<?php
			$qry_office = mysqli_query($connection,"select * from tbl_office order by office_name asc");
			for($a=1;$a<=mysqli_num_rows($qry_office);$a++){
				$rows = mysqli_fetch_assoc($qry_office);
				echo "<tr>";
				echo "<td>&nbsp;&nbsp;$rows[office_code]</td>";

				echo "<td>&nbsp;&nbsp;$rows[office_name]</td>";

				//$qry_undue = mysqli_query($connection,"select *,(a.office_code)res_office,((a.office_time-d.office_time)/d.office_time)totalofficedelayed from tbl_document_transaction a, tbl_document b, tbl_office c, tbl_office_performance d where a.barcode=b.barcode and a.office_code=c.office_code and a.office_code=d.office_code and d.document_code=b.document_type and a.office_time<d.office_time and a.office_code='$rows[office_code]' and a.recieve_date_time like '$date%'");

				$qry_undue = mysqli_query($connection,"select distinct a.barcode from tbl_document_transaction a, tbl_document b, tbl_office c, tbl_office_performance d where a.barcode=b.barcode and a.office_code=c.office_code and a.office_code=d.office_code and d.document_code=b.document_type and a.office_code='$rows[office_code]'");

				//$qry_delin = mysqli_query($connection,"select *,(a.office_code)res_office,((a.office_time-d.office_time)/d.office_time)totalofficedelayed from tbl_document_transaction a, tbl_document b, tbl_office c, tbl_office_performance d where a.barcode=b.barcode and a.office_code=c.office_code and a.office_code=d.office_code and d.document_code=b.document_type and a.office_time>d.office_time and a.office_code='$rows[office_code]' and a.recieve_date_time like '$date%'");

				$qry_delin = mysqli_query($connection,"select * from tbl_document_transaction a, tbl_document b, tbl_office c, tbl_office_performance d where a.barcode=b.barcode and a.office_code=c.office_code and a.office_code=d.office_code and d.document_code=b.document_type and a.office_time>d.office_time and a.office_code='$rows[office_code]'");


				$undue = mysqli_num_rows($qry_undue);
				$delin = mysqli_num_rows($qry_delin);
				$total = $undue+$delin;

				echo "<td align='center'>".number_format($undue)."</td>";
				echo "<td align='center'>".number_format($delin)."</td>";
				echo "<td align='center'>".number_format($total)."</td>";
				echo "</tr>";
			}

			?>
		</table>
		<br>
		Generated By: <?php echo $_REQUEST['user']; ?>
		<br>
		Date: <?php echo date("M d, Y");?>

	</div>
</body>
</html>
