<?php
	include("../database/database_connection.php");
  	include_once('../functions/login_functions.php');
 	verify_valid_system_user();

 	$system_user = $_SESSION['valid_dts_user'];
	$qry_access = mysqli_query($connection,"select * from tbl_users where username='$system_user'");
	$access = mysqli_fetch_assoc($qry_access);
?>
<!DOCTYPE html>
<html>
<head>
	<title>Document Tracking System</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../bootstrap/css/bootstrap.min.css">
	<script src="../bootstrap/js/jquery.min.js"></script>
	<script src="../bootstrap/js/bootstrap.min.js"></script>
	<!-- other css -->
	<link rel="stylesheet" href="../bootstrap/css/designs.min.css">

	<!-- For Tables -->
	<link rel="stylesheet" href="../bootstrap/css/dataTables.min.css">
	<script type="text/javascript" src="../bootstrap/js/dataTables.min.js"></script>
	<link rel="icon" href="../images/dts.png" type="image/gif" sizes="16x16">
</head>
<body>
	<?php
	/*------------date-------------------*/
	$date_from_display = $_REQUEST['frommm']."/".$_REQUEST['fromdd']."/".$_REQUEST['fromyyyy'];
	$date_to_display = $_REQUEST['tomm']."/".$_REQUEST['todd']."/".$_REQUEST['toyyyy'];

	$date = $_REQUEST['toyyyy']."-".$_REQUEST['tomm']."-".$_REQUEST['todd'];
	$date1 = str_replace('-', '/', $date);
	$tomorrow = date('Y-m-d',strtotime($date1 . "+1 days"));

	$tomorrow;

	$date_from = $_REQUEST['fromyyyy']."-".$_REQUEST['frommm']."-".$_REQUEST['fromdd'];
	$date_to = $tomorrow;

	include('../functions/time_functions.php');

	$qry_wh = mysqli_query($connection,"select timestampdiff(minute,time_start,time_end)as working_minutes from tbl_working_hours");
	$wh = mysqli_fetch_assoc($qry_wh);
	?>
	<div class="container-report-delin">
		<table class="table-report">
			<tr>
				<td colspan="2" style="text-align: center;"><h4>DOCUMENT TRACKING SYSTEM REPORT</h4></td>
			</tr>
			<tr>
				<td style="width:150px;">REPORT TYPE:</td>
				<td>Delinquent Transactions</td>
			</tr>
			<tr>
				<td style="width:150px;">DATE RANGE:</td>
				<td><?php echo $date_from_display." to ".$date_to_display?></td>
			</tr>
		</table>
		<br>
		<table class="table-report" border="1">
			<tr align="center" style="font-weight: bold;">
				<td style="width: 120px;">Barcode</td>
				<td>Office</td>
				<td style="width: 150px;">Receive</td>
				<td style="width: 150px;">Release</td>
				<td style="width: 100px;">Duration</td>
			</tr>
			<!-- <tr align="center" style="font-weight: bold;">
				<td width="100px;">On-time</td>
				<td width="100px;">Deliquent</td>
				<td width="100px;">Total</td>
			</tr> -->
			<?php
			$qry_office = mysqli_query($connection,"select *,DATE_FORMAT(a.recieve_date_time,'%b. %d, %Y - %h:%i')rcv,DATE_FORMAT(a.release_date_time,'%b. %d, %Y - %h:%i')rel,(a.office_time)tme from tbl_document_transaction a, tbl_document b, tbl_office c, tbl_office_performance d where a.barcode=b.barcode and a.office_code=c.office_code and a.office_code=d.office_code and d.document_code=b.document_type and a.office_time>d.office_time and a.recieve_date_time between '$date_from' and '$date_to' order by a.office_time desc");
			
			

			for($a=1;$a<=mysqli_num_rows($qry_office);$a++){
				$rows = mysqli_fetch_assoc($qry_office);
				echo "<tr>";
				echo "<td align='left'>&nbsp; $a. <a href='../forms/tracking_result.php?barcode=$rows[barcode]&acode=$rows[access_code]' target='_blank'>".ucwords($rows['barcode'])."</a></td>";
				echo "<td>&nbsp;&nbsp;$rows[office_code] - $rows[office_name]</td>";
				echo "<td align='center'>$rows[rcv]</td>";
				echo "<td align='center'>$rows[rel]</td>";
				echo "<td align='center'>".convert_time($rows['tme'])."</td>";
				echo "</tr>";
			}

			?>
		</table>
		<br>
		Generated By: <?php echo $_REQUEST['user']; ?>
		<br>
		Date: <?php echo date("M d, Y");?>

	</div>
</body>
</html>